### ISSUE TITLE
Text Editor has odd gap

### ISSUE THREAD

**Issue by cmaughan** [yorkdayofcode/yorkdayofcode.github.io#15]
When I type text, the cursor is ahead of where I type.  Sometimes there is an empty box there too.

**Comment by cmaughan** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fad905f92e8400112fda9b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a17873d3e52be71429575d5a18ac415a5946fdfa8d29afa42062c80d55b98e30063e937f03a6aa8316b500bf238b488cb0bd8f49c4ec3937aa.PNG)

**Comment by kevbite** [comment]
Looks like a feature

**Comment by DavidBetteridge** [comment]
Sorted - removed the code which changed the font family.
